language: java
# use Java 8
jdk:
- oraclejdk8

dist: trusty
# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: true

# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  
before_install:
  - chmod +x mvnw